import React, { useState } from 'react';
import { Alert, Pressable, Share, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Button, Card, Divider, EmptyState, ErrorCard, Field, Heading, Icon, Label, Pill, Row, Screen, TopBar } from '../components/ui';
import { MOCK } from '../data/mockData';
import { dateLabel, errorMessage, money, serviceFor } from '../lib/helpers';
import { useApp } from '../state/AppContext';
import { useTheme } from '../theme';
import type { PaymentMethod, RootStackParamList } from '../types';

export function PaymentScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, 'Payment'>) {
  const theme = useTheme(); const { requests, completeRequest } = useApp(); const request = requests.find(item => item.id === route.params.requestId);
  const [method, setMethod] = useState<PaymentMethod>('transfer'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const pay = async () => {
    if (!request || busy) return;
    setBusy(true); setError('');
    try { await completeRequest(request.id, method); navigation.replace('Receipt', { requestId: request.id }); }
    catch (err) { setError(errorMessage(err)); } finally { setBusy(false); }
  };
  if (!request) return <Screen><TopBar title="Payment" onBack={() => navigation.popToTop()} /><EmptyState title="Request not found" body="Return to your request history." /></Screen>;
  if (request.status === 'completed') return <Screen><TopBar title="Payment recorded" onBack={() => navigation.popToTop()} /><Button title="View demo receipt" onPress={() => navigation.replace('Receipt', { requestId: request.id })} /></Screen>;
  if (request.status !== 'arrived') return <Screen><TopBar title="Payment" onBack={() => navigation.goBack()} /><EmptyState title="Not ready for payment" body="Your simulated provider must arrive first." /></Screen>;
  return <Screen><TopBar title="Payment" onBack={() => navigation.goBack()} /><Pill text="STEP 3 OF 3 · WRAP IT UP" /><Heading subtitle="Choose how you’d like to pay in this demo.">Back on your way.</Heading>
    <Card style={{ alignItems: 'center', paddingVertical: 28 }}><Label size={13} color={theme.secondary}>TOTAL · {serviceFor(request.serviceId).name.toUpperCase()}</Label><Label size={45} weight="800" color={theme.primaryText} style={{ letterSpacing: -2 }}>{money(request.quote.total)}</Label><Pill text={MOCK.paymentLabel} tone="amber" /></Card>
    <Label size={18} weight="700">Payment method</Label>
    {(['transfer', 'card', 'cash'] as PaymentMethod[]).map(value => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: method === value, disabled: busy }} disabled={busy} onPress={() => setMethod(value)}><Card style={{ borderColor: method === value ? theme.primaryText : theme.border, borderWidth: method === value ? 2 : 1, padding: 18 }}><Row><View style={{ backgroundColor: theme.tint, padding: 11, borderRadius: 12 }}><Icon name={value === 'transfer' ? 'repeat' : value === 'card' ? 'credit-card' : 'pocket'} color={theme.primaryText} /></View><View style={{ flex: 1 }}><Label weight="700">{value === 'transfer' ? 'Bank transfer' : value === 'card' ? 'Debit / credit card' : 'Cash'}</Label><Label size={12} color={theme.secondary}>{value === 'transfer' ? 'Simulate transfer confirmation' : value === 'card' ? 'No card details collected' : 'Simulate paying your provider'}</Label></View><Icon name={method === value ? 'check-circle' : 'circle'} color={method === value ? theme.primaryText : theme.secondary} /></Row></Card></Pressable>)}
    <Card style={{ backgroundColor: theme.tint }}>{method === 'transfer' ? <><Label weight="700">Demo transfer details</Label><Label size={13}>{MOCK.transfer.bank}</Label><Label size={21} weight="800">{MOCK.transfer.account}</Label><Label size={12} color={theme.secondary}>{MOCK.transfer.beneficiary}</Label><Label size={12} color={theme.primaryText}>This is not a real account. Do not transfer money. The button below only records a local demo payment.</Label></> : <><Row><Icon name="info" color={theme.primaryText} /><Label weight="700">{method === 'card' ? 'Mock card checkout' : 'Mock cash confirmation'}</Label></Row><Label size={13} color={theme.secondary}>{method === 'card' ? 'No card form or payment gateway is connected. Never enter real card details in this prototype.' : 'No cash is collected. This simply marks the sample request as paid by cash.'}</Label></>}</Card>
    <Card><Row style={{ justifyContent: 'space-between' }}><Label color={theme.secondary}>Service</Label><Label>{money(request.quote.base)}</Label></Row><Row style={{ justifyContent: 'space-between' }}><Label color={theme.secondary}>Dispatch</Label><Label>{money(request.quote.dispatch)}</Label></Row><Divider /><Row style={{ justifyContent: 'space-between' }}><Label weight="700">Total</Label><Label weight="800">{money(request.quote.total)}</Label></Row></Card>
    {!!error && <ErrorCard message={error} onRetry={() => { void pay(); }} />}<Button title={busy ? 'Simulating payment…' : method === 'transfer' ? 'Simulate transfer confirmation' : method === 'card' ? `Simulate paying ${money(request.quote.total)}` : 'Record simulated cash payment'} loading={busy} icon="check-circle" onPress={() => { void pay(); }} /><Label size={11} color={theme.secondary} style={{ textAlign: 'center' }}>No real transaction. This is not proof of payment.</Label>
  </Screen>;
}
export function ReceiptScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'Receipt'>) {
  const theme = useTheme(); const { requests, rateRequest } = useApp(); const request = requests.find(item => item.id === route.params.requestId);
  const [rating, setRating] = useState(request?.rating ?? 0); const [review, setReview] = useState(request?.review ?? ''); const [saved, setSaved] = useState(false);
  if (!request || request.status !== 'completed') return <Screen><TopBar title="Receipt" onBack={() => navigation.popToTop()} /><EmptyState title="No receipt yet" body="Finish your demo service and mock payment first." /></Screen>;
  const share = async () => {
    try { await Share.share({ title: `${MOCK.appName} demo receipt`, message: `${MOCK.appName} — DEMO RECEIPT\nNOT PROOF OF PAYMENT\n${request.id}\n${dateLabel(request.completedAt ?? request.createdAt)}\n${serviceFor(request.serviceId).name}\nService: ${money(request.quote.base)}\nDispatch: ${money(request.quote.dispatch)}\nTotal: ${money(request.quote.total)}\nMethod: ${request.paymentMethod}\nNo real money was paid. This is a simulated request.` }); }
    catch (err) { Alert.alert('Could not share receipt', errorMessage(err)); }
  };
  return <Screen><TopBar title="Your receipt" onBack={() => navigation.popToTop()} /><View style={{ alignItems: 'center', gap: 13, paddingVertical: 12 }}><View style={{ backgroundColor: theme.tint, padding: 21, borderRadius: 60 }}><Icon name="check-circle" size={46} color={theme.primaryText} /></View><Label size={28} weight="800">You’re good to go.</Label><Label color={theme.secondary}>Thanks for taking the demo for a spin.</Label><Pill text="DEMO RECEIPT · NOT PROOF OF PAYMENT" tone="amber" /></View>
    <Card><Label size={12} color={theme.secondary}>{request.id} · {dateLabel(request.completedAt ?? request.createdAt)}</Label><Label size={22} weight="700">{serviceFor(request.serviceId).name}</Label><Label size={13} color={theme.secondary}>{request.locationLabel}</Label><Divider /><Row style={{ justifyContent: 'space-between' }}><Label color={theme.secondary}>Service</Label><Label>{money(request.quote.base)}</Label></Row><Row style={{ justifyContent: 'space-between' }}><Label color={theme.secondary}>Dispatch</Label><Label>{money(request.quote.dispatch)}</Label></Row><Divider /><Row style={{ justifyContent: 'space-between' }}><Label weight="700">Simulated total</Label><Label size={26} weight="800" color={theme.primaryText}>{money(request.quote.total)}</Label></Row><Pill text={`${request.paymentMethod ?? 'DEMO'} · SIMULATED`.toUpperCase()} /><Label size={11} color={theme.secondary}>No real funds were transferred or collected.</Label></Card>
    <Card><Label size={19} weight="700">How was the demo?</Label><Label size={13} color={theme.secondary}>Rate your simulated experience with {MOCK.provider.name}</Label><Row style={{ justifyContent: 'space-between', gap: 0 }}>{[1, 2, 3, 4, 5].map(value => <Pressable key={value} accessibilityRole="radio" accessibilityLabel={`${value} star${value > 1 ? 's' : ''}`} accessibilityState={{ checked: rating === value }} onPress={() => { setRating(value); setSaved(false); }} style={{ padding: 7, minWidth: 44, minHeight: 46, justifyContent: 'center', alignItems: 'center' }}><Icon name="star" size={31} color={value <= rating ? theme.accent : theme.border} /></Pressable>)}</Row><Field label="Your feedback (optional)" value={review} onChangeText={value => { setReview(value); setSaved(false); }} placeholder="What went well?" maxLength={500} multiline style={{ minHeight: 85 }} /><Button title={saved ? 'Rating saved on this phone' : request.rating ? 'Update rating' : 'Save rating'} disabled={!rating} variant="secondary" icon={saved ? 'check' : 'star'} onPress={() => { rateRequest(request.id, rating, review.trim()); setSaved(true); }} /></Card>
    <Button title="Share demo receipt" variant="secondary" icon="share-2" onPress={() => { void share(); }} /><Button title="Back to home" icon="arrow-right" onPress={() => navigation.popToTop()} />
  </Screen>;
}
