export type Coordinate = { latitude: number; longitude: number };
export type ServiceId = 'tow' | 'battery' | 'tyre' | 'fuel' | 'mechanic' | 'lockout';
export type Service = { id: ServiceId; name: string; description: string; icon: 'truck' | 'zap' | 'disc' | 'droplet' | 'tool' | 'key'; basePrice: number; eta: string };
export type PaymentMethod = 'transfer' | 'card' | 'cash';
export type ThemeMode = 'system' | 'light' | 'dark';
export type RequestStatus = 'en_route' | 'arrived' | 'completed' | 'cancelled';
export type Quote = { base: number; dispatch: number; total: number };
export type RoadRequest = {
  id: string;
  serviceId: ServiceId;
  createdAt: string;
  completedAt?: string;
  location: Coordinate;
  locationLabel: string;
  locationSource: 'demo' | 'device' | 'manual';
  vehicle: string;
  notes: string;
  quote: Quote;
  status: RequestStatus;
  progress: number;
  paymentMethod?: PaymentMethod;
  rating?: number;
  review?: string;
};
export type RequestDraft = Pick<RoadRequest, 'serviceId' | 'location' | 'locationLabel' | 'locationSource' | 'vehicle' | 'notes'>;
export type EmergencyContact = { id: string; name: string; phone: string };
export type ProviderJob = { id: string; customer: string; serviceId: ServiceId; distance: string; locationLabel: string; vehicle: string; earnings: number; status: 'incoming' | 'accepted' | 'declined' | 'completed' };
export type Settings = { theme: ThemeMode; providerMode: boolean; emergencyContacts: EmergencyContact[]; providerContactPhone: string };
export type RootStackParamList = {
  Welcome: undefined;
  Phone: undefined;
  OTP: { phone: string };
  Main: undefined;
  Request: { serviceId: ServiceId };
  Estimate: { draft: RequestDraft };
  Tracking: { requestId: string };
  Payment: { requestId: string };
  Receipt: { requestId: string };
  SOS: undefined;
};
export type MainTabParamList = { Home: undefined; History: undefined; Provider: undefined; Settings: undefined };
